//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inovix.KGBAccountCustomer {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="KGBAccountCustomer.IAccountCustomer")]
    public interface IAccountCustomer {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountCustomer/DoWork", ReplyAction="http://tempuri.org/IAccountCustomer/DoWorkResponse")]
        void DoWork();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountCustomer/DoWork", ReplyAction="http://tempuri.org/IAccountCustomer/DoWorkResponse")]
        System.Threading.Tasks.Task DoWorkAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountCustomer/ObterDadosConta", ReplyAction="http://tempuri.org/IAccountCustomer/ObterDadosContaResponse")]
        Inovix.Data.Account ObterDadosConta(Inovix.Data.Customer customer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountCustomer/ObterDadosConta", ReplyAction="http://tempuri.org/IAccountCustomer/ObterDadosContaResponse")]
        System.Threading.Tasks.Task<Inovix.Data.Account> ObterDadosContaAsync(Inovix.Data.Customer customer);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAccountCustomerChannel : Inovix.KGBAccountCustomer.IAccountCustomer, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AccountCustomerClient : System.ServiceModel.ClientBase<Inovix.KGBAccountCustomer.IAccountCustomer>, Inovix.KGBAccountCustomer.IAccountCustomer {
        
        public AccountCustomerClient() {
        }
        
        public AccountCustomerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AccountCustomerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AccountCustomerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AccountCustomerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void DoWork() {
            base.Channel.DoWork();
        }
        
        public System.Threading.Tasks.Task DoWorkAsync() {
            return base.Channel.DoWorkAsync();
        }
        
        public Inovix.Data.Account ObterDadosConta(Inovix.Data.Customer customer) {
            return base.Channel.ObterDadosConta(customer);
        }
        
        public System.Threading.Tasks.Task<Inovix.Data.Account> ObterDadosContaAsync(Inovix.Data.Customer customer) {
            return base.Channel.ObterDadosContaAsync(customer);
        }
    }
}
