//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InovixTeste.KGBFinanceiro {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="KGBFinanceiro.IFinanceiro")]
    public interface IFinanceiro {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFinanceiro/DoWork", ReplyAction="http://tempuri.org/IFinanceiro/DoWorkResponse")]
        void DoWork();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFinanceiro/DoWork", ReplyAction="http://tempuri.org/IFinanceiro/DoWorkResponse")]
        System.Threading.Tasks.Task DoWorkAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFinanceiro/ObterStatusFinanceiroCliente", ReplyAction="http://tempuri.org/IFinanceiro/ObterStatusFinanceiroClienteResponse")]
        int ObterStatusFinanceiroCliente(string cpf);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFinanceiro/ObterStatusFinanceiroCliente", ReplyAction="http://tempuri.org/IFinanceiro/ObterStatusFinanceiroClienteResponse")]
        System.Threading.Tasks.Task<int> ObterStatusFinanceiroClienteAsync(string cpf);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFinanceiroChannel : InovixTeste.KGBFinanceiro.IFinanceiro, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FinanceiroClient : System.ServiceModel.ClientBase<InovixTeste.KGBFinanceiro.IFinanceiro>, InovixTeste.KGBFinanceiro.IFinanceiro {
        
        public FinanceiroClient() {
        }
        
        public FinanceiroClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FinanceiroClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FinanceiroClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FinanceiroClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void DoWork() {
            base.Channel.DoWork();
        }
        
        public System.Threading.Tasks.Task DoWorkAsync() {
            return base.Channel.DoWorkAsync();
        }
        
        public int ObterStatusFinanceiroCliente(string cpf) {
            return base.Channel.ObterStatusFinanceiroCliente(cpf);
        }
        
        public System.Threading.Tasks.Task<int> ObterStatusFinanceiroClienteAsync(string cpf) {
            return base.Channel.ObterStatusFinanceiroClienteAsync(cpf);
        }
    }
}
