//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YUMWebService.KGBCustomer {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Customer", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Customer : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdCustomerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CpfField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private YUMWebService.KGBCustomer.Address AddressField;
        
        private YUMWebService.KGBCustomer.StatusFinanceiro StatusFinanceiroField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int IdCustomer {
            get {
                return this.IdCustomerField;
            }
            set {
                if ((this.IdCustomerField.Equals(value) != true)) {
                    this.IdCustomerField = value;
                    this.RaisePropertyChanged("IdCustomer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Cpf {
            get {
                return this.CpfField;
            }
            set {
                if ((object.ReferenceEquals(this.CpfField, value) != true)) {
                    this.CpfField = value;
                    this.RaisePropertyChanged("Cpf");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public YUMWebService.KGBCustomer.Address Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public YUMWebService.KGBCustomer.StatusFinanceiro StatusFinanceiro {
            get {
                return this.StatusFinanceiroField;
            }
            set {
                if ((this.StatusFinanceiroField.Equals(value) != true)) {
                    this.StatusFinanceiroField = value;
                    this.RaisePropertyChanged("StatusFinanceiro");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Address", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Address : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StreetField;
        
        private int NumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ComplementField;
        
        private int CepField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int IdAddress {
            get {
                return this.IdAddressField;
            }
            set {
                if ((this.IdAddressField.Equals(value) != true)) {
                    this.IdAddressField = value;
                    this.RaisePropertyChanged("IdAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Street {
            get {
                return this.StreetField;
            }
            set {
                if ((object.ReferenceEquals(this.StreetField, value) != true)) {
                    this.StreetField = value;
                    this.RaisePropertyChanged("Street");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int Number {
            get {
                return this.NumberField;
            }
            set {
                if ((this.NumberField.Equals(value) != true)) {
                    this.NumberField = value;
                    this.RaisePropertyChanged("Number");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Complement {
            get {
                return this.ComplementField;
            }
            set {
                if ((object.ReferenceEquals(this.ComplementField, value) != true)) {
                    this.ComplementField = value;
                    this.RaisePropertyChanged("Complement");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int Cep {
            get {
                return this.CepField;
            }
            set {
                if ((this.CepField.Equals(value) != true)) {
                    this.CepField = value;
                    this.RaisePropertyChanged("Cep");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StatusFinanceiro", Namespace="http://tempuri.org/")]
    public enum StatusFinanceiro : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InadimplenteInterno = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InadimplenteOutraOperadora = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InadimplenteExterno = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Apto = 3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="KGBCustomer.CustomerWebServiceSoap")]
    public interface CustomerWebServiceSoap {
        
        // CODEGEN: Generating message contract since element name cpf from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCustomerByCpf", ReplyAction="*")]
        YUMWebService.KGBCustomer.GetCustomerByCpfResponse GetCustomerByCpf(YUMWebService.KGBCustomer.GetCustomerByCpfRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCustomerByCpfRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCustomerByCpf", Namespace="http://tempuri.org/", Order=0)]
        public YUMWebService.KGBCustomer.GetCustomerByCpfRequestBody Body;
        
        public GetCustomerByCpfRequest() {
        }
        
        public GetCustomerByCpfRequest(YUMWebService.KGBCustomer.GetCustomerByCpfRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCustomerByCpfRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string cpf;
        
        public GetCustomerByCpfRequestBody() {
        }
        
        public GetCustomerByCpfRequestBody(string cpf) {
            this.cpf = cpf;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCustomerByCpfResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCustomerByCpfResponse", Namespace="http://tempuri.org/", Order=0)]
        public YUMWebService.KGBCustomer.GetCustomerByCpfResponseBody Body;
        
        public GetCustomerByCpfResponse() {
        }
        
        public GetCustomerByCpfResponse(YUMWebService.KGBCustomer.GetCustomerByCpfResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCustomerByCpfResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public YUMWebService.KGBCustomer.Customer GetCustomerByCpfResult;
        
        public GetCustomerByCpfResponseBody() {
        }
        
        public GetCustomerByCpfResponseBody(YUMWebService.KGBCustomer.Customer GetCustomerByCpfResult) {
            this.GetCustomerByCpfResult = GetCustomerByCpfResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CustomerWebServiceSoapChannel : YUMWebService.KGBCustomer.CustomerWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CustomerWebServiceSoapClient : System.ServiceModel.ClientBase<YUMWebService.KGBCustomer.CustomerWebServiceSoap>, YUMWebService.KGBCustomer.CustomerWebServiceSoap {
        
        public CustomerWebServiceSoapClient() {
        }
        
        public CustomerWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CustomerWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CustomerWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CustomerWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        YUMWebService.KGBCustomer.GetCustomerByCpfResponse YUMWebService.KGBCustomer.CustomerWebServiceSoap.GetCustomerByCpf(YUMWebService.KGBCustomer.GetCustomerByCpfRequest request) {
            return base.Channel.GetCustomerByCpf(request);
        }
        
        public YUMWebService.KGBCustomer.Customer GetCustomerByCpf(string cpf) {
            YUMWebService.KGBCustomer.GetCustomerByCpfRequest inValue = new YUMWebService.KGBCustomer.GetCustomerByCpfRequest();
            inValue.Body = new YUMWebService.KGBCustomer.GetCustomerByCpfRequestBody();
            inValue.Body.cpf = cpf;
            YUMWebService.KGBCustomer.GetCustomerByCpfResponse retVal = ((YUMWebService.KGBCustomer.CustomerWebServiceSoap)(this)).GetCustomerByCpf(inValue);
            return retVal.Body.GetCustomerByCpfResult;
        }
    }
}
